steps:

  #- name: 'gcr.io/ecommerce-434317/sonar-scanner:latest'
  #  args:
  #  - '-Dsonar.host.url=https://sonarcloud.io'
  #  - '-Dsonar.login=68b6ef9ccb6730fe9ef96d7ab708265d9a63aae0'
  #  - '-Dsonar.projectKey=gt0593sonarcloud_basic-nodejs-app'
  #  - '-Dsonar.organization=gt0593sonarcloud'
  #  - '-Dsonar.sources=.'

  - name: node
    entrypoint: npm
    args: ['install']

  - name: 'ubuntu'
    entrypoint: 'bash'
    args: ['-c', 'mkdir /workspace/.scannerwork']

  - name: 'ubuntu'
    entrypoint: 'bash'
    args: ['-c', 'chown 1000:1000 /workspace/.scannerwork']

  - name: 'ubuntu'
    entrypoint: 'bash'
    args: ['-c', 'chmod -R 777 /workspace/.scannerwork']

  - name: 'ubuntu'
    entrypoint: 'bash'
    args: ['-c', 'ls']

  - name: 'ubuntu'
    entrypoint: 'bash'
    args: ['-c', 'ls -la /workspace']
    
  - name: 'us-central1-docker.pkg.dev/ecommerce-434317/sonar-scanner/sonar-scanner:5'
    entrypoint: 'sonar-scanner'
    args:
      - '-X'
      - '-Dsonar.host.url=https://sonarcloud.io'
      - '-Dsonar.projectKey=gt0593sonarcloud_basic-nodejs-app'
      - '-Dsonar.organization=gt0593sonarcloud'
      - '-Dsonar.exclusions=Dockerfile,**/*.html,**/*.json,tests/**,**/*.yaml'
      - '-Dsonar.javascript.lcov.reportPaths=coverage/lcov.info'
      - '-Dsonar.sources=.'
  #    - '-Dsonar.tests=tests'
    env:
      - SONAR_TOKEN=2021fdd9704fb6d5378fcf9e817a873ee027bc46
    
    # Build the container image using definition on Dockerfile
  #- name: 'gcr.io/cloud-builders/docker'
  #  args: ['build', '-t', 'us-central1-docker.pkg.dev/ecommerce-434317/basic-nodejs-app/basic-nodejs-app:$COMMIT_SHA', '.']

    # Push the container image to Artifact Registry
  #- name: 'gcr.io/cloud-builders/docker'
  #  args: ['push', 'us-central1-docker.pkg.dev/ecommerce-434317/basic-nodejs-app/basic-nodejs-app:$COMMIT_SHA']
    # Deploy container image to Cloud Run
  #- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  #  entrypoint: gcloud
  #  args:
  #  - 'run'
  #  - 'deploy'
  #  - 'basic-nodejs-app'
  #  - '--image'
  #  - 'us-central1-docker.pkg.dev/ecommerce-434317/basic-nodejs-app/basic-nodejs-app:$COMMIT_SHA'
  #  - '--region'
  #  - 'us-central1'
images:
  - 'us-central1-docker.pkg.dev/ecommerce-434317/basic-nodejs-app/basic-nodejs-app:$COMMIT_SHA'
options:
  logging: CLOUD_LOGGING_ONLY
