steps:
    # Build the container image using definition on Dockerfile
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/ecommerce-434317/basic-nodejs-app/basic-nodejs-app:$COMMIT_SHA', '.']

  #- name: 'gcr.io/ecommerce-434317/sonar-scanner:latest'
  #  args:
  #  - '-Dsonar.host.url=https://sonarcloud.io'
  #  - '-Dsonar.login=68b6ef9ccb6730fe9ef96d7ab708265d9a63aae0'
  #  - '-Dsonar.projectKey=gt0593sonarcloud_basic-nodejs-app'
  #  - '-Dsonar.organization=gt0593sonarcloud'
  #  - '-Dsonar.sources=.'

  - name: 'us-docker.pkg.dev/xer-demo-devops-prd/sonar-scanner/sonar-scanner:latest'
    entrypoint: 'sonar-scanner'
    args:
      - '-Dsonar.host.url=https://sonarcloud.io'
      - '-Dsonar.projectKey=gt0593sonarcloud_basic-nodejs-app'
      - '-Dsonar.organization=gt0593sonarcloud'
      - '-Dsonar.exclusions=Dockerfile,**/*.html,**/*.json,tests/**,**/*.yaml'
      - '-Dsonar.javascript.lcov.reportPaths=coverage/lcov.info'
      - '-Dsonar.sources=.'
      - '-Dsonar.tests=tests'
    env:
      - SONAR_TOKEN=68b6ef9ccb6730fe9ef96d7ab708265d9a63aae0
    
    # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/ecommerce-434317/basic-nodejs-app/basic-nodejs-app:$COMMIT_SHA']
    # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'run'
    - 'deploy'
    - 'basic-nodejs-app'
    - '--image'
    - 'us-central1-docker.pkg.dev/ecommerce-434317/basic-nodejs-app/basic-nodejs-app:$COMMIT_SHA'
    - '--region'
    - 'us-central1'
images:
  - 'us-central1-docker.pkg.dev/ecommerce-434317/basic-nodejs-app/basic-nodejs-app:$COMMIT_SHA'
options:
  logging: CLOUD_LOGGING_ONLY
